# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "box-cutter/oel70"
  config.vm.network "forwarded_port", guest: 8080, host: 8888
  #config.vm.synced_folder "/apps", "/vagrant_apps"


  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/vagrant.yml"
  end
  
  
end
